services:
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_Db: postgres

  backend:
    build: .
    depends_on:
      - db
    restart: always
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    stdin_open: true
    tty: true
    
  nginx:
    image: nginx
    depends_on:
      - backend
      - certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email virajbaswana@gmail.com -d app.virajbaswana.com --agree-tos

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: