services:

  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_Db: postgres

  backend:
    build: .
    depends_on:
      - db
    restart: always
    env_file: ./.env
    ports:
      - 80:3000
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    stdin_open: true
    tty: true
    


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: