FROM node as builder

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

COPY . .

# RUN npm run build

# COPY . .
CMD [ "npm", "run" , "dev" ]