services:

  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_Db: marketing_automation


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: